### ISSUE TITLE
How to calculate stride and padding for deconvolution 

### ISSUE THREAD

**Issue by seeni-dev** [pgtgrly/Convolution-Deconvolution-Network-Pytorch#2]
your code used some values for convolution and deconvolution. But how did you arrive at those values for deconvolution ? It will be useful if you can share links to articles and your insights on this

**Comment by pgtgrly** [comment]
In case of maxunpooling we are storing the size and indices into [variables](https://github.com/pgtgrly/Convolution-Deconvolution-Network-Pytorch/blob/bbf09ccfe20e282134b84aa4e056b7594702312d/Neural_Network_Class.py#L54). 
As for the formula. A simple google search yields [this](https://stackoverflow.com/questions/35980044/getting-the-output-shape-of-deconvolution-layer-using-tf-nn-conv2d-transpose-in).

**Comment by seeni-dev** [comment]
no. It is just output shape of convolution. I want to know how you fixed stride and padding of deconvolution layer?

**Comment by pgtgrly** [comment]
did you look into the second link which I provided?

**Comment by seeni-dev** [comment]
I did. that is for convolution. you can also see comments asking for deconvolution but there is no response. Just add the expressions in your code. it will help others.

**Comment by pgtgrly** [comment]
[This](https://stackoverflow.com/a/49347788) is the first answer in the link which I provided. It clearly states the formula.

**Comment by seeni-dev** [comment]
Did you see that was a clear derivation from output_size of convolution. Those params( strides,kernel_size and padding) are from convolution, not deconvolution.

**Comment by seeni-dev** [comment]
can you express them like (W−F+2P)/S+1 for deconvolution? Notice that in  `output_size = strides * (input_size-1) + kernel_size - 2*padding` , strides *(input_size-1) makes it harder to simplify the equation.

**Comment by pgtgrly** [comment]
O = S*(W-1)+F - 2*P
